"""Tool-call protocols: how tools are offered to the model and how calls come back.

``native``       OpenAI ``tools``; llama-server (``--jinja``) parses calls and
                 applies its lazy tool-call grammar.
``json_schema``  ``response_format`` JSON schema over an action envelope.
``grammar``      GBNF generated by argus for the same envelope.

All protocols validate arguments harness-side, so a bad call always becomes an
error result the model can recover from.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any

from argus import schema as js
from argus.config import AgentConfig
from argus.providers.base import Completion
from argus.tools.base import Tool


@dataclass
class ToolCall:
    id: str
    name: str
    args: dict[str, Any]
    raw: str
    error: str | None = None  # set when the call is malformed
    salvaged: bool = False  # recovered from text the server failed to parse


@dataclass
class Parsed:
    calls: list[ToolCall] = field(default_factory=list)
    final: str | None = None  # final answer; the run ends
    content: str = ""  # visible text of the turn
    problems: list[str] = field(default_factory=list)  # malformed output with no call to attach to
    assistant: dict[str, Any] = field(default_factory=dict)  # history entry for this turn

    @property
    def malformed(self) -> list[str]:
        return [c.error for c in self.calls if c.error] + self.problems


# Markup that means the model tried to call a tool but the server did not parse it.
TOOL_MARKUP = re.compile(r"<tool_call>|<function=|<\|tool_call|\[TOOL_CALLS\]|<tools>")
HERMES_CALL = re.compile(r"<tool_call>\s*(\{.*?\})\s*(?:</tool_call>|$)", re.S)
XML_CALL = re.compile(r"<function=([\w.-]+)>(.*?)(?:</function>|$)", re.S)
XML_PARAM = re.compile(r"<parameter=([\w.-]+)>\n?(.*?)\n?</parameter>", re.S)


def check_call(tools: dict[str, Tool], call: ToolCall) -> ToolCall:
    """Validate a call's name and arguments, filling ``call.error``."""
    if call.error:
        return call
    tool = tools.get(call.name)
    if tool is None:
        call.error = f"unknown tool {call.name!r}; available: {', '.join(tools)}"
        return call
    if not isinstance(call.args, dict):
        call.error = f"arguments for {call.name} must be a JSON object"
        return call
    call.args = js.coerce(call.args, tool.parameters)
    problems = js.validate(call.args, tool.parameters)
    if problems:
        call.error = f"invalid arguments for {call.name}: " + "; ".join(problems)
    return call


def decode_args(raw: str) -> tuple[dict[str, Any] | None, str | None]:
    text = raw.strip() or "{}"
    try:
        value = json.loads(text)
    except json.JSONDecodeError as e:
        return None, f"arguments are not valid JSON ({e.msg} at char {e.pos})"
    if not isinstance(value, dict):
        return None, "arguments must be a JSON object"
    return value, None


def salvage_calls(text: str, turn: int) -> list[ToolCall]:
    """Recover Hermes/Qwen-style calls that were left in plain text."""
    calls: list[ToolCall] = []
    for i, m in enumerate(HERMES_CALL.finditer(text)):
        try:
            obj = json.loads(m.group(1))
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict) and isinstance(obj.get("name"), str):
            args = obj.get("arguments", obj.get("parameters", {}))
            if isinstance(args, str):
                args, _ = decode_args(args)
            calls.append(
                ToolCall(f"call_{turn}_s{i}", obj["name"], args or {}, m.group(1), salvaged=True)
            )
    if calls:
        return calls
    for i, m in enumerate(XML_CALL.finditer(text)):
        params = {k: _xml_value(v) for k, v in XML_PARAM.findall(m.group(2))}
        calls.append(ToolCall(f"call_{turn}_s{i}", m.group(1), params, m.group(0), salvaged=True))
    return calls


def _xml_value(v: str) -> Any:
    s = v.strip()
    if s in ("true", "false"):
        return s == "true"
    if re.fullmatch(r"-?\d+", s):
        return int(s)
    return v


class Protocol:
    name = "base"

    def __init__(self, tools: dict[str, Tool], cfg: AgentConfig):
        self.tools = tools
        self.cfg = cfg

    def request_fields(self) -> dict[str, Any]:
        return {}

    def prompt_section(self) -> str:
        """Text appended to the system prompt (tool list, output format)."""
        return ""

    def finish_hint(self) -> str:
        return "When the task is done, reply with a short summary and no tool call."

    def parse(self, c: Completion, turn: int) -> Parsed:
        raise NotImplementedError

    def result_message(self, call: ToolCall, text: str) -> dict[str, Any]:
        raise NotImplementedError

    def feedback_message(self, text: str) -> dict[str, Any]:
        return {"role": "user", "content": text}

    def disable_thinking(self) -> dict[str, Any]:
        return {"thinking": {"enabled": False}}


class NativeProtocol(Protocol):
    name = "native"

    def request_fields(self) -> dict[str, Any]:
        if not self.tools:
            return {}
        return {
            "tools": [t.schema() for t in self.tools.values()],
            "tool_choice": self.cfg.tool_choice,
            "parallel_tool_calls": self.cfg.parallel_tool_calls,
        }

    def parse(self, c: Completion, turn: int) -> Parsed:
        p = Parsed(content=c.content)
        for i, raw in enumerate(c.tool_calls):
            args, err = decode_args(raw.arguments)
            call = ToolCall(raw.id or f"call_{turn}_{i}", raw.name, args or {}, raw.arguments, err)
            p.calls.append(check_call(self.tools, call))
        if not p.calls and c.malformed:
            p.problems.append(c.malformed + "; call tools with the function-calling format")
        elif not p.calls and TOOL_MARKUP.search(c.content):
            salvaged = salvage_calls(c.content, turn)
            if salvaged:
                p.calls = [check_call(self.tools, s) for s in salvaged]
            else:
                p.problems.append(
                    "your tool call was not in a format the server could parse; "
                    "call tools with the function-calling format"
                )
        if not p.calls and not p.problems:
            if c.content.strip():
                p.final = c.content.strip()
            else:
                p.problems.append("empty reply; call a tool or give your final answer")
        p.assistant = self._assistant(c, p)
        return p

    def _assistant(self, c: Completion, p: Parsed) -> dict[str, Any]:
        msg: dict[str, Any] = {"role": "assistant", "content": c.content}
        if p.calls:
            # Salvaged calls came from content; keep content free of the markup.
            if any(call.salvaged for call in p.calls):
                msg["content"] = TOOL_MARKUP.split(c.content, 1)[0].strip()
            msg["tool_calls"] = [
                {
                    "id": call.id,
                    "type": "function",
                    "function": {
                        "name": call.name,
                        # Invalid JSON in history can break template rendering server-side.
                        "arguments": json.dumps(call.args if not call.error else {}),
                    },
                }
                for call in p.calls
            ]
        if self.cfg.keep_reasoning and c.reasoning:
            msg["reasoning_content"] = c.reasoning
        if c.replay:
            msg["replay"] = c.replay
        return msg

    def result_message(self, call: ToolCall, text: str) -> dict[str, Any]:
        return {"role": "tool", "tool_call_id": call.id, "content": text}


DONE_PARAMS = {
    "type": "object",
    "properties": {"summary": {"type": "string"}},
    "required": ["summary"],
    "additionalProperties": False,
}
THINK_BLOCK = re.compile(r"^\s*(?:<think>)?(.*?)</think>\s*", re.S)


def envelope_schema(tools: dict[str, Tool], thought: bool) -> dict[str, Any]:
    """``{"thought"?, "tool", "args"}`` with one branch per tool, so args are checked per tool."""
    branches = []
    for name, params in [*((t.name, t.parameters) for t in tools.values()), ("done", DONE_PARAMS)]:
        props: dict[str, Any] = {}
        if thought:
            props["thought"] = {"type": "string"}
        props["tool"] = {"const": name}
        props["args"] = params
        branches.append(
            {
                "type": "object",
                "properties": props,
                "required": list(props),
                "additionalProperties": False,
            }
        )
    return {"anyOf": branches}


class ConstrainedProtocol(Protocol):
    """One JSON action per turn; the server constrains output to the envelope."""

    def prompt_section(self) -> str:
        shape = '{"tool": NAME, "args": {...}}'
        if self.cfg.json_thought:
            shape = '{"thought": "brief reasoning", "tool": NAME, "args": {...}}'
        lines = [f"Reply with exactly one JSON action per turn: {shape}", "Tools:"]
        lines += [t.signature() for t in self.tools.values()]
        lines.append("done(summary) - finish; summarise what you did")
        return "\n".join(lines)

    def finish_hint(self) -> str:
        return "When the task is done, use done."

    def schema(self) -> dict[str, Any]:
        return envelope_schema(self.tools, self.cfg.json_thought)

    def parse(self, c: Completion, turn: int) -> Parsed:
        text = c.content
        m = THINK_BLOCK.match(text)
        if m:  # the server did not split the reasoning out (reasoning_format=none)
            text = text[m.end() :]
        p = Parsed(content=text)
        p.assistant = {"role": "assistant", "content": text.strip()}
        if self.cfg.keep_reasoning and c.reasoning:
            p.assistant["reasoning_content"] = c.reasoning
        stripped = text.strip()
        if not stripped:
            p.problems.append("empty reply; reply with one JSON action")
            return p
        try:
            action = json.loads(stripped)
        except json.JSONDecodeError as e:
            p.problems.append(f"reply is not a valid JSON action ({e.msg} at char {e.pos})")
            return p
        if not isinstance(action, dict) or not isinstance(action.get("tool"), str):
            p.problems.append('reply must be a JSON object with "tool" and "args"')
            return p
        # the visible text is the action's thought; the call itself is shown as a call
        p.content = action["thought"] if isinstance(action.get("thought"), str) else ""
        args = action.get("args", {})
        if action["tool"] == "done":
            summary = args.get("summary") if isinstance(args, dict) else None
            p.final = summary if isinstance(summary, str) else json.dumps(args)
            return p
        call = ToolCall(
            f"call_{turn}_0", action["tool"], args if isinstance(args, dict) else {}, stripped
        )
        if not isinstance(args, dict):
            call.error = f"args for {call.name} must be a JSON object"
        p.calls.append(check_call(self.tools, call))
        return p

    def result_message(self, call: ToolCall, text: str) -> dict[str, Any]:
        # Qwen templates render tool results exactly like this inside a user turn.
        return {"role": "user", "content": f"<tool_response>\n{text}\n</tool_response>"}


class JsonSchemaProtocol(ConstrainedProtocol):
    """``response_format`` JSON schema; llama-server compiles it to a grammar."""

    name = "json_schema"

    def request_fields(self) -> dict[str, Any]:
        return {
            "response_format": {
                "type": "json_schema",
                "json_schema": {"name": "action", "strict": True, "schema": self.schema()},
            },
            # A schema constrains output from the first token, which would forbid a
            # <think> block; model.enable_thinking = true overrides this.
            **self.disable_thinking(),
        }


class GrammarProtocol(ConstrainedProtocol):
    """GBNF generated by argus: compact JSON, fixed key order, optional <think> prefix."""

    name = "grammar"

    def __init__(self, tools: dict[str, Tool], cfg: AgentConfig):
        super().__init__(tools, cfg)
        from argus.gbnf import schema_to_gbnf

        self.grammar = schema_to_gbnf(self.schema(), think=cfg.grammar_think)

    def request_fields(self) -> dict[str, Any]:
        return {"grammar": self.grammar}


PROTOCOLS: dict[str, type[Protocol]] = {
    "native": NativeProtocol,
    "json_schema": JsonSchemaProtocol,
    "grammar": GrammarProtocol,
}


def make_protocol(name: str, tools: dict[str, Tool], cfg: AgentConfig) -> Protocol:
    if name not in PROTOCOLS:
        raise ValueError(f"unknown protocol {name!r}; choose from {', '.join(PROTOCOLS)}")
    return PROTOCOLS[name](tools, cfg)
