"""Tool-call protocols: how tools are offered to the model and how calls come back.

``native``       OpenAI ``tools``; llama-server (``--jinja``) parses calls and
                 applies its lazy tool-call grammar.
``json_schema``  ``response_format`` JSON schema over an action envelope.
``grammar``      GBNF generated by argus for the same envelope.

All protocols validate arguments harness-side, so a bad call always becomes an
error result the model can recover from.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any

from argus import schema as js
from argus.config import AgentConfig
from argus.llm import Completion
from argus.tools.base import Tool


@dataclass
class ToolCall:
    id: str
    name: str
    args: dict[str, Any]
    raw: str
    error: str | None = None  # set when the call is malformed
    salvaged: bool = False  # recovered from text the server failed to parse


@dataclass
class Parsed:
    calls: list[ToolCall] = field(default_factory=list)
    final: str | None = None  # final answer; the run ends
    content: str = ""  # visible text of the turn
    problems: list[str] = field(default_factory=list)  # malformed output with no call to attach to
    assistant: dict[str, Any] = field(default_factory=dict)  # history entry for this turn

    @property
    def malformed(self) -> list[str]:
        return [c.error for c in self.calls if c.error] + self.problems


# Markup that means the model tried to call a tool but the server did not parse it.
TOOL_MARKUP = re.compile(r"<tool_call>|<function=|<\|tool_call|\[TOOL_CALLS\]|<tools>")
HERMES_CALL = re.compile(r"<tool_call>\s*(\{.*?\})\s*(?:</tool_call>|$)", re.S)
XML_CALL = re.compile(r"<function=([\w.-]+)>(.*?)(?:</function>|$)", re.S)
XML_PARAM = re.compile(r"<parameter=([\w.-]+)>\n?(.*?)\n?</parameter>", re.S)


def check_call(tools: dict[str, Tool], call: ToolCall) -> ToolCall:
    """Validate a call's name and arguments, filling ``call.error``."""
    if call.error:
        return call
    tool = tools.get(call.name)
    if tool is None:
        call.error = f"unknown tool {call.name!r}; available: {', '.join(tools)}"
        return call
    if not isinstance(call.args, dict):
        call.error = f"arguments for {call.name} must be a JSON object"
        return call
    call.args = js.coerce(call.args, tool.parameters)
    problems = js.validate(call.args, tool.parameters)
    if problems:
        call.error = f"invalid arguments for {call.name}: " + "; ".join(problems)
    return call


def decode_args(raw: str) -> tuple[dict[str, Any] | None, str | None]:
    text = raw.strip() or "{}"
    try:
        value = json.loads(text)
    except json.JSONDecodeError as e:
        return None, f"arguments are not valid JSON ({e.msg} at char {e.pos})"
    if not isinstance(value, dict):
        return None, "arguments must be a JSON object"
    return value, None


def salvage_calls(text: str, turn: int) -> list[ToolCall]:
    """Recover Hermes/Qwen-style calls that were left in plain text."""
    calls: list[ToolCall] = []
    for i, m in enumerate(HERMES_CALL.finditer(text)):
        try:
            obj = json.loads(m.group(1))
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict) and isinstance(obj.get("name"), str):
            args = obj.get("arguments", obj.get("parameters", {}))
            if isinstance(args, str):
                args, _ = decode_args(args)
            calls.append(
                ToolCall(f"call_{turn}_s{i}", obj["name"], args or {}, m.group(1), salvaged=True)
            )
    if calls:
        return calls
    for i, m in enumerate(XML_CALL.finditer(text)):
        params = {k: _xml_value(v) for k, v in XML_PARAM.findall(m.group(2))}
        calls.append(ToolCall(f"call_{turn}_s{i}", m.group(1), params, m.group(0), salvaged=True))
    return calls


def _xml_value(v: str) -> Any:
    s = v.strip()
    if s in ("true", "false"):
        return s == "true"
    if re.fullmatch(r"-?\d+", s):
        return int(s)
    return v


class Protocol:
    name = "base"

    def __init__(self, tools: dict[str, Tool], cfg: AgentConfig):
        self.tools = tools
        self.cfg = cfg

    def request_fields(self) -> dict[str, Any]:
        return {}

    def prompt_section(self) -> str:
        """Text appended to the system prompt (tool list, output format)."""
        return ""

    def finish_hint(self) -> str:
        return "When the task is done, reply with a short summary and no tool call."

    def parse(self, c: Completion, turn: int) -> Parsed:
        raise NotImplementedError

    def result_message(self, call: ToolCall, text: str) -> dict[str, Any]:
        raise NotImplementedError

    def feedback_message(self, text: str) -> dict[str, Any]:
        return {"role": "user", "content": text}

    def disable_thinking(self) -> dict[str, Any]:
        return {"chat_template_kwargs": {"enable_thinking": False}}


class NativeProtocol(Protocol):
    name = "native"

    def request_fields(self) -> dict[str, Any]:
        if not self.tools:
            return {}
        return {
            "tools": [t.schema() for t in self.tools.values()],
            "tool_choice": self.cfg.tool_choice,
            "parallel_tool_calls": self.cfg.parallel_tool_calls,
        }

    def parse(self, c: Completion, turn: int) -> Parsed:
        p = Parsed(content=c.content)
        for i, raw in enumerate(c.tool_calls):
            args, err = decode_args(raw.arguments)
            call = ToolCall(raw.id or f"call_{turn}_{i}", raw.name, args or {}, raw.arguments, err)
            p.calls.append(check_call(self.tools, call))
        if not p.calls and TOOL_MARKUP.search(c.content):
            salvaged = salvage_calls(c.content, turn)
            if salvaged:
                p.calls = [check_call(self.tools, s) for s in salvaged]
            else:
                p.problems.append(
                    "your tool call was not in a format the server could parse; "
                    "call tools with the function-calling format"
                )
        if not p.calls and not p.problems:
            p.final = c.content.strip()
        p.assistant = self._assistant(c, p)
        return p

    def _assistant(self, c: Completion, p: Parsed) -> dict[str, Any]:
        msg: dict[str, Any] = {"role": "assistant", "content": c.content}
        if p.calls:
            # Salvaged calls came from content; keep content free of the markup.
            if any(call.salvaged for call in p.calls):
                msg["content"] = TOOL_MARKUP.split(c.content, 1)[0].strip()
            msg["tool_calls"] = [
                {
                    "id": call.id,
                    "type": "function",
                    "function": {
                        "name": call.name,
                        # Invalid JSON in history can break template rendering server-side.
                        "arguments": json.dumps(call.args if not call.error else {}),
                    },
                }
                for call in p.calls
            ]
        if self.cfg.keep_reasoning and c.reasoning:
            msg["reasoning_content"] = c.reasoning
        return msg

    def result_message(self, call: ToolCall, text: str) -> dict[str, Any]:
        return {"role": "tool", "tool_call_id": call.id, "content": text}


def make_protocol(name: str, tools: dict[str, Tool], cfg: AgentConfig) -> Protocol:
    if name == "native":
        return NativeProtocol(tools, cfg)
    raise ValueError(f"unknown protocol {name!r}")
